### ISSUE TITLE
怎么直接使用该预训练模型输出embedding

### ISSUE THREAD

**Issue by zilinly** [ZhuiyiTechnology/roformer-sim#19]

**Comment by yinchunlin** [comment]
同问？麻烦回答一下，非常感谢

**Comment by yinchunlin** [comment]
同问

**Comment by yinchunlin** [comment]
def similarity_former(text1, text2):
    """"计算text1与text2的相似度
    """
    texts = [text1, text2]
    X, S = [], []
    for t in texts:
        x, s = tokenizer.encode(t, maxlen=maxlen)
        # print(x ,s)
        X.append(x)
        S.append(s)
    X = sequence_padding(X)
    S = sequence_padding(S)
    Z = encoder.predict([X, S])
    #print(Z)
    Z /= (Z**2).sum(axis=1, keepdims=True)**0.5
    print(Z )
    return (Z[0] * Z[1]).sum()



在这个函数中的“Z /= (Z**2).sum(axis=1, keepdims=True)**0.5”就是吧

**Comment by zilinly** [comment]
已解决

**Comment by yinchunlin** [comment]
只是在这里对两个句向量计算相似度用的是这个方式，为什么不用余弦相似度、哈夫曼等方式呢(Z[0] * Z[1]).sum()

**Comment by zilinly** [comment]
> 

两个问题吧，第一步是先计算文本的embedding，然后考虑计算相似度的方式，考虑到性能的问题，可能会选择向量数据库来解决相似度的问题
